### ISSUE TITLE
update script

### ISSUE THREAD

**Issue by arist0v** [createcandle/candle-controller#25]
need to make an update script or something similar to allow user to easily update the candle controller to the last release

**Comment by flatsiedatsie** [comment]
Yes.

The tech for this exists and has been tested. It only works on the latest version of the disk image.

- A prototype script that only does `apt-get update; apt-get upgade` already exists, and is part of the Powrer Settings addon:
https://github.com/createcandle/power-settings/blob/master/manual_update.sh

You can try it yourself by entering developer mode, and then opening the updates page under settings. It will then allow you to do a "manual update".

- The `factory reset script` is probably also a good startingpoint:
https://github.com/createcandle/power-settings/blob/master/factory_reset.sh

- As well as the `restore backup` script:
https://github.com/createcandle/power-settings/blob/master/restore_backup.sh

There is purposefully enough space on the system partition to do a simultanous double install, so the new version can be installed alongside the old one, and if it works the old version can then be deleted by a second script. This is how Webthings has worked so far.

A future version might just swap out a docker container instead?

**Comment by arist0v** [comment]
i was meaning a way to update candle from 2.0.0 to 2.0.1 to 2.1.1. to 3.x.x

**Comment by flatsiedatsie** [comment]
The disk image creation script is now also the system update script. It needs more testing, but seems to work so far.
