### ISSUE TITLE
RPi: first boot doesn't complete or reboot?

### ISSUE THREAD

**Issue by mlavi** [createcandle/candle-controller#34]
I have a Raspberry Pi 4b with ethernet connected and Candle 2.0.0 (May 27) installed.

First (re)boot never seems to complete with the web interface available over the static DHCP address given by my DHCP server, although I do see the Raspberry Pi 4b (over ethernet) does take the static IPv4 lease and also gets a dynamic IPv6 lease with hostname candle.

After about 10 minutes, I had to hard power cycle the Pi, then the web interface comes up at the desired static DHCP IPv4 address assigned.

**Comment by mlavi** [comment]
Some more detail and an example: I use OpenWRT and dhcpd to associate a hostname, MAC address, and IPv4 static lease to 192.168.1.214 on my LAN.

![candle-june14-dhcpd-static-leases](https://user-images.githubusercontent.com/5642075/174632198-0584a128-5d0e-475d-add3-ee933288d1d9.png)

You can see that works, but first boot during Candlestick install also picks up an IPv6 dynamic lease reporting a hostname of: candle. Regardless, Candle doesn't respect the static IPv4 lease assigned: it doesn't ping or otherwise respond.

**Comment by flatsiedatsie** [comment]
Do you have any suggestions on how to fix this?

**Comment by mlavi** [comment]
I installed RC2 and RC3 today, first boot for both came up fine on the DHCP address and the web admin console responded!

**Comment by flatsiedatsie** [comment]
Great to hear :-)
