### ISSUE TITLE
RPi: default ssh password incorrect?

### ISSUE THREAD

**Issue by mlavi** [createcandle/candle-controller#35]
I have a Raspberry Pi 4b with ethernet connected and Candle 2.0.0 (May 27) installed.

I read the boot/readme.txt file to learn how to unlock developer settings in the web interface: I enabled SSH there and now I can ssh pi@DHCP, but it does not accept candlesmarthome as the password. Do I have the wrong password?

**Comment by arist0v** [comment]
Have you try raspberry as password??

**Comment by mlavi** [comment]
Yes, that failed as well.

**Comment by arist0v** [comment]
does it work using the seashell addons?

**Comment by mlavi** [comment]
Aha, I didn't know about seashell, thanks!

`mkdir ~/.ssh && echo 'ssh-ed25519 example_hash example_comment' > ~/.ssh/authorized_keys`

I am in now via `ssh pi@pi`

**Comment by arist0v** [comment]
Yes but your bypassing the auth process with ssh key

Le lun. 20 juin 2022, 20 h 47, Mark Lavi ***@***.***> a
écrit :

**Comment by mlavi** [comment]
Yes, I used seashell to execute the commands to set my SSH key for authentication to bypass password authentication.

Once I was SSH'd in, I confirmed that user pi's password is not either of the two suggestions, because I could not change the password:

```shell
pi@candle:/var/log $ passwd
Changing password for pi.
Current password: 
passwd: Authentication token manipulation error
passwd: password unchanged
pi@candle:/var/log $ passwd
Changing password for pi.
Current password: 
passwd: Authentication token manipulation error
passwd: password unchanged
```
Seashell doesn't execute commands over ssh, it runs commands locally on the OS: https://github.com/flatsiedatsie/seashell/blob/master/pkg/seashell.py#L166

**Comment by flatsiedatsie** [comment]
Apologies, I just noticed that the readme.txt file mentioned the wrong password. It's `smarthome`, not `candlesmarthome`.

**Comment by mlavi** [comment]
Just returned from a trip and confirmed, yes `smarthome` is the password!

Thanks for correcting [readme.txt](https://github.com/createcandle/configuration-files/commit/e21833e07456bb144866a4e2deee134645c22143
), I recommend referencing this issue in the commit.
